CREATE TABLE IF NOT EXISTS threads (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  thread_name VARCHAR(25) NOT NULL,
  user_name VARCHAR(25) DEFAULT 'nobody',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
